---
title: "Section 1.3: Regular Expressions"
output: 
  revealjs::revealjs_presentation:
    fig_width: 14 
    fig_height: 7
    self_contained: true
    theme: night
    highlight: zenburn
    css: slidesdjh.css
    center: false
    transition: slide
    reveal_options:
      controls: true
      progress: false
      width: 1080
      height: 540
---

# Languages and Automata

## So far...

- **Regular Languages** are languages that are recognized by DFA's
- We have proved:
    + DFA's can simulate NFA's, so we can use NFA's instead.
    + Regular languages are closed under **regular operations** $\cup$, $\circ$, $*$

# Regular Expressions

## Describing Languages

So far, we have specified particular languages a couple ways:

- Set builder notation: $\{w \mid \text{some property of } w\}$
- The language recognized by a given machine.

Today we will describe them using **regular expressions.**

## Example: Star notation

Star notation was handy for expressing "give me all the ways to combine this set of strings."

- Prework #2
- $\{0 ,1\}^*$

Regular expressions allow concatination, union, and star.

## Definition of a Regular Expression

$R$ is a **regular expression** if $R$ is:

1. $a$, for some $a\in \Sigma$,
2. $\varepsilon$
3. $\emptyset$
4.  $R_1 \cup R_2$, where $R_1$ and $R_2$ are regular expressions.
5. $R_1\circ R_2$,  where $R_1$ and $R_2$ are regular expressions.
6. $R_1^*$, where $R_1$ is a regular expression.

Notice that this is a **recursive definition**.

## Interpreting Regular Expressions

Let $\Sigma = 0\cup 1 = \{0,1\}$. What languages are these?

1. $1\Sigma$ *$\quad$ (This is how we write $1\circ \Sigma$.)*
2. $1\Sigma^*$
3. $(\Sigma\Sigma)^*$
4. $1^*01^+$ *$\quad$ ($a^+$ is shorthand for $aa^*$)*
5. $1^*(01^+)^*$
6. $(0\cup\varepsilon)1$
7. $\Sigma\emptyset$
8. $\emptyset^*$

## Writing Regular Expressions

Which regular expressions define these languages over $\Sigma = \{0,1\}$?

1. $\{w \mid w \text{ starts with a 1 and ends with a 0} \}$
2. $\{w \mid w \text{ contains 01 as a substring} \}$
3. $\{w \mid w \text{ contains an odd number of 1's} \}$

# Are Regular Expressions the same as regular languages?

## Regular Expression $\Rightarrow$ Regular Language

Lemma 1.55. If a language is described by a regular expression, then it is a regular language.

Proof: Use induction on the recursive definition.

## Use the proof to construct an NFA

Follow the logic of the proof to build an NFA that recognizes $(ab \cup a)^*$.

# Applications

## Some examples of using grep

https://www.digitalocean.com/community/tutorials/using-grep-regular-expressions-to-search-for-text-patterns-in-linux

## Lexical Analyzers ("lexers")

Numerical constants can be integers, decimals, possibly with leading 0's, possibly with +/- signs.

- $D = \{0,1,2,3,4,5,6,7,8,9\}$
- $\Sigma = D \cup \{+, -, .\}$

Numerical constant:

$$
(+ \cup - \cup \varepsilon)(D^+ \cup D^+.D^* \cup D^*.D^+)
$$
