---
title: "Section 1.4: More Pumping Lemma Proofs"
output:
  revealjs::revealjs_presentation:
    center: no
    css: slidesdjh.css
    fig_height: 7
    fig_width: 14
    highlight: zenburn
    reveal_options:
      controls: yes
      height: 600
      progress: no
      width: 1080
    reveal_plugins: notes
    self_contained: no
    theme: black
    transition: slide
  html_document:
    self_contained: true
    theme: spacelab
    code_download: true
  pdf_document:
    keep_tex: true
    includes:
      in_header: notesheader.tex
date: "January 22, 2020"
---

```{r include=FALSE}
set.seed(12120)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

# Prework Presentations

## 1. [`r paste(fnames[1:3], sep = ',')`] 

Read Example 1.75 on page 81. The last line of the third paragraph states, "With condition 3 the proof follows because $y$ must consist of only \texttt{0}s, so $xyyz\not\in F$." Explain, in more detail than is given in the book, why $xyyz\not\in F$.

## 2. [`r paste(fnames[4:6], sep = ',')`] 

In the last sentence of Example 1.75, it says that the string $\mathtt{0}^p\mathtt{0}^p$ "can be pumped." Explain, what this means, and, specifically, how it can be pumped.

## 3. [`r paste(fnames[7:9], sep = ',')`] 

Use the Pumping Lemma to show that the language $A = \{www \mid w \in \{\mathtt{a},\mathtt{b}\}^*\}$ is not regular.

# Pumping Lemma Proof Techniques

## Pumping Lemma {data-transition="slide-in fade-out"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.


##  Pumping Down {data-transition="fade"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

**Pumping down** is the process of reaching a contradiction using $i=0$ in step 1.

Example: Use the Pumping Lemma to prove that $A=\{0^i1^j \mid i > j \}$ is not a regular language.

## Using Closure {data-transition="fade-in slide-out"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

Regular languages are **closed** under $\cap, \cup, \circ, \overline{\phantom{X}}, *$, XOR.

Example: Prove that the language $A = \{w \mid w \text{ has the same number of 1's as 0's}\}$ is nonregular.

## Unary languages and numbers {data-transition="slide-in fade-out"}

A **unary** language is a language over an alphabet with one symbol, e.g., $\Sigma = \{\mathtt{0}\}$.

- Strings in the language have the form $\mathtt{0}^k$, for $k\geq 0$.
- Strings correspond to numbers ($\mathtt{0}^k \leftrightarrow k$).
- Languages correspond to sets of numbers.
- Regular expressions correspond to DFA's that can tell if a number belongs to a particular set!

## Unary languages and numbers {data-transition="fade-in slide-out"}

A **unary** language is a language over an alphabet with one symbol, e.g., $\Sigma = \{\mathtt{0}\}$.

- Strings in the language have the form $\mathtt{0}^k$, for $k\geq 0$.
- Strings correspond to numbers ($\mathtt{0}^k \leftrightarrow k$).
- Languages correspond to sets of numbers.
- Regular expressions correspond to DFA's that can tell if a number belongs to a particular set!
    + $\{\mathtt{0}^{2k} \mid k\geq 0\}$ (the even numbers) is regular. (why?)
    + $\{\mathtt{0}^{k^2} \mid k\geq 0\}$ (the perfect squares) is nonregular. (next slide)

## A nonregular Unary language 

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

Example: Use the Pumping Lemma to prove that $A=\{\mathtt{0}^{n^2} \mid n \in \mathbb{N}\}$ is not a regular language.

