---
title: "Section 1.4: Nonregular Languages"
output: 
  revealjs::revealjs_presentation:
    fig_width: 14 
    fig_height: 7
    self_contained: true
    theme: night
    highlight: zenburn
    css: slidesdjh.css
    center: false
    transition: slide
    reveal_options:
      controls: true
      progress: false
      width: 1080
      height: 540
---

# Regular Languages

## Facts about Regular Languages

- Regular languages are (by definition) those that are recognized by DFA's.
- Regular languages are also those that are recognized by NFA's (and also GNFA's).
- The set of all regular languages is closed under the regular operations $\cup$, $\circ$, $*$, as well as other operations, such as complement, $\cap$, and XOR.
- Regular languages are those that are described by regular expressions.

These facts all provide ways to show that a given language *is* regular.

# Nonregular languages

## The Pumping Lemma {data-background="https://media.giphy.com/media/xTiTniUuclWObMLD32/giphy.gif"}

## Proving a language is not regular

- Given a language that you want to prove is nonregular, Assume, to the contrary, that it is regular, and find a contradiction.
- i.e., show that the given language fails to have a property that all regular languages must have.
- One such property is the **Pumping Lemma**.

## Pumping Lemma {data-transition="slide-in fade-out"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

(Discuss Proof)

## Using the Pumping Lemma {data-transition="fade"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

Example #1: Use the Pumping Lemma to prove that $A=\{0^n1^n \mid n \in \mathbb{N}\}$ is not a regular language.

## Using the Pumping Lemma {data-transition="fade"}

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

Example #2: Use the Pumping Lemma to prove that $A=\{1^{n^2} \mid n \in \mathbb{N}\}$ is not a regular language.

