---
title: "Section 1.4: Regular Languages Review"
output:
  revealjs::revealjs_presentation:
    center: no
    css: slidesdjh.css
    fig_height: 7
    fig_width: 14
    highlight: zenburn
    reveal_options:
      controls: yes
      height: 600
      progress: no
      width: 1080
    reveal_plugins: notes
    self_contained: no
    theme: black
    transition: slide
  html_document:
    self_contained: true
    theme: spacelab
    code_download: true
  pdf_document:
    keep_tex: true
    includes:
      in_header: notesheader.tex
date: "January 24, 2020"
---

```{r include=FALSE}
set.seed(12220)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

# Prework Presentations

## 2. [`r paste(fnames[1:3], sep = ',')`] 

A *palindrome* is a string that reads the same forwards as backwards. For example, 00011000 is a palindrome, but 101010 is not. Prove that the language
$$
A = \{w \mid w \text{ is not a palindrome}\}
$$
is not a regular language, where $\Sigma = \{0,1\}$.

## 3. [`r paste(fnames[4:6], sep = ',')`] 

We proved that the language $A = \{0^n1^n \mid n \geq 0\}$ is nonregular by pumping up. Redo this proof, but instead, pump down.

## 4. [`r paste(fnames[7:9], sep = ',')`] 

Prove that the following language is nonregular.
$$
A = \{\underbrace{1^n0^*1^n0^*1^n0^* \cdots 1^n}_{k \; 1^n\text{'s}} \mid k\geq 2, \; n\geq 0 \}
$$
Hint: Consider $A \cap (1^*01^*)$.

## Pumping Lemma

*Theorem 1.70 (Pumping Lemma).* If $A$ is a regular language, then there is a number $p$ (the "pumping length") such that, if $s\in A$ has length at least $p$, then $s = xyz$, where:

1. for each $i \geq 0$, $xy^iz \in A$,
2. $|y| > 0$, and
3. $|xy| \leq p$.

# Regular vs Nonregular

## How to prove a language is regular

- Build a DFA or an NFA that recognizes it.
- Find a regular expression that describes it.
- Use closure to show that it is made of regular languages.

## How to prove a language is nonregular

- Pumping lemma argument
- Closure argument

## Why are some languages regular and others nonregular?

Consider the following two languages. Are they regular or nonregular?

$$
B =  \lbrace 1^k y \mid y \in \lbrace 0, 1\rbrace^\star \text { and } y \text{ contains at least } k \text{ 1's, for } k \geq 1 \rbrace 
$$
$$
C =  \{1^k y \mid y \in \{0, 1\}^\star \text{ and } y \text{ contains at most } k \text{ 1's, for } k \geq 1 \} 
$$

## Other closure operations

Given a language $A$, define its *reverse* $A^R$ to be the language consisting of all of the strings in $A$ taken backwards (e.g., $\{011, 100, 10\}^R = \{110, 001, 01\}$).

- Prove that the regular languages are closed under the reverse operation.

## Formal DFA definition

A **finite automaton** (DFA) is a 5-tuple $(Q, \Sigma, \delta, q_0, F)$, where

1. $Q$ is a finite set called the **states**,
2. $\Sigma$ is a finite set called the **alphabet**,
3. $\delta: Q \times \Sigma \longrightarrow Q$ is the **transition function**,
4. $q_0 \in Q$ is the **start state**, and
5. $F \subseteq Q$ is the set of **accept states**.

## Formal NFA definition

A **nondeterministic finite automaton** (NFA) is a 5-tuple $(Q, \Sigma, \delta, q_0, F)$, where

1. $Q$ is a finite set called the **states**,
2. $\Sigma$ is a finite set called the **alphabet**,
3. $\delta: Q \times (\Sigma \cup \{\varepsilon\}) \longrightarrow \mathcal{P}(Q)$ is the **transition function**,
4. $q_0 \in Q$ is the **start state**, and
5. $F \subseteq Q$ is the set of **accept states**.

## More interesting symbols

Consider $\Sigma = \left\lbrace \frac{0}{0}, \frac{0}{1}, \frac{1}{0}, \frac{1}{1}  \right\rbrace$. A string in $\Sigma^\ast$ consists of a top binary string $t$ and a bottom binary string $b$ of equal lengths. Which of the following languages are regular?

$$
D =  \left\lbrace w = \frac{t}{b} \in \Sigma^\ast \mid t \text{ is the reverse of } b \right\rbrace 
$$
$$
E =  \left\lbrace w = \frac{t}{b} \in \Sigma^\ast \mid t > b \text{ as binary numbers} \right\rbrace 
$$


