---
title: "Section 3.3: The Church-Turing Thesis"
output:
  pdf_document:
    keep_tex: true
    fig_width: 3
    fig_height: 3
    includes:
      in_header: notesheader.tex
  revealjs::revealjs_presentation:
    center: no
    css: slidesdjh.css
    fig_height: 7
    fig_width: 14
    highlight: zenburn
    reveal_options:
      controls: yes
      height: 600
      progress: no
      width: 1080
    reveal_plugins: notes
    self_contained: no
    theme: black
    transition: slide
  html_document:
    self_contained: true
    theme: spacelab
    code_download: true
date: "February 19, 2020"
---

```{r include=FALSE}
set.seed(21420)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

# Prework Presentations

## 1. [`r paste(fnames[1:3], sep = ',')`]  

How many different ways can you divide the string $\mathtt{abcd}$ into nonempty substrings $w_1, w_2, \ldots, w_k$, for $k \geq 1$, such that $w_1w_2\cdots w_k = w$? How about $\mathtt{abcde}$? Can you describe an organized method for running through each possible division?

## 3. [`r paste(fnames[4:6], sep = ',')`] 

Let $M_3$ be a TM that recognizes a language $B$. Explain how to build a TM that recognizes $B^\ast$. 

## 4. [`r paste(fnames[7:9], sep = ',')`] 

Suppose that $M_4$ is a TM that decides a language $C$. Describe a simple way to contstruct a TM that decides $\overline{C}$, the complement of $C$. Explain why this construction would not be so simple if $M$ were just a recognizer, and not a decider.

# Models of computation

## Machines and languages

- DFA's. 
    - Same as NFA's, GNFA's, regular expressions.
    - Recognize *regular languages*.
- PDA's 
    - Same as context-free grammars.
    - Recognize *context-free* languages.
- TM's
    - Same as multitape, nondeterministic TM's
    - Recognize *Turing-recognizable* languages.
    - Decide *decidable* languages.

# Algorithms

## "Definition" of an algorithm

> An *algorithm* is a well-defined computational procedure that takes some value, or set of values, as input and produces some value, or set of values, as output.  [Cormen, et. al.] 

## Describing algorithms (high level)

We describe algorithms in prose or *pseudocode*. We need to be able to do the following.

- Store and retrieve data (variables).
- Branch on a condition (if-then-else)
- Repeat steps until a condition changes (while- and for-loops).
- Add, subtract, multiply.
- Compare values for equality.
- ???

**Church-Turing Thesis:** Any task that be done by an algorithm can be done by a Turing Machine.

## Church-Turing Thesis

$$
\text{Intuitive notion of algorithms} = \text{Turing machine algorithms}
$$

- The TM model of computation is *robust*: Adding features to it does not change the set of languages it can recognize or decide.
    - Key features: RAM, finite number of states, finite amount of work done at each step.
- Any machine that can emulate a TM is as computationally powerful as any other machine (questions of efficiency aside).
- Any *limitations* of TM's are limitations of computers in general!

## Computable functions

- A function $f:\Sigma^\ast \longrightarrow \Sigma^\ast$ is called *computable* if some Turing machine $M$, on every input $w$, enters the accept state with just $f(w)$ on its tape.
- If strings can represent any type of input and output, then algorithms ("well-defined computational procedures that take some value as input and produce some value as output") are computable functions.

# Encoding Mathematical Objects

## Representing with strings

Any discrete/finite mathematical object can be represented as a string.

- Natural numbers, integers, rational numbers
- Polynomials, roots of polynomials
- Graphs (vertices and edges)
- DFA's, NFA's, PDA's, TM's
- etc.

TM's can accept any of these as input, given a suitable encoding.

## Example: Graphs

- An (undirected) graph is a list of vertices and edges (finite sets).
- Encoding: $\mathtt{(}\text{vertex list}\mathtt{)}\mathtt{(}\text{edge list}\mathtt{)}$
- Example: $\mathtt{(1,2,3,4)((1,2),(2,3),(3,1),(1,4))}$ 
    - Draw the graph.

## High-level TM description 

On input $\langle G \rangle$, the encoding of a graph $G$:

1. Mark the first vertex of $G$.
2. Repeat Step 3 until no new vertices are marked: 
3. For each vertex $v$ in $G$, mark if it shares an edge with a previously marked vertex.
4. Scan all vertices of $G$. If they are all marked, accept. Otherwise, reject.

What language is decided/recognized?

## Example: polynomials

