---
title: "Section 4.2: An Undecidable Language"
output:
  revealjs::revealjs_presentation:
    center: no
    css: slidesdjh.css
    fig_height: 7
    fig_width: 14
    highlight: zenburn
    reveal_options:
      controls: yes
      height: 600
      progress: no
      width: 1080
    reveal_plugins: notes
    self_contained: no
    theme: black
    transition: slide
  html_document:
    self_contained: true
    theme: spacelab
    code_download: true
  pdf_document:
    keep_tex: true
    fig_width: 3
    fig_height: 3
    includes:
      in_header: notesheader.tex
date: "March 4, 2020"
---

```{r include=FALSE}
set.seed(3220)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

# Prework Presentations

## 1. [`r paste(fnames[1:3], sep = ',')`] 

Let $\mathcal{B}$ be the set of all infinite binary sequences. Use a diagonalization argument to explain why $\mathcal{B}$ is uncountable.

## 3. [`r paste(fnames[4:6], sep = ',')`] 

- In class we described a TM $M$ that decided the language $A_\text{CFG} = \{\langle G, w \rangle \mid G \text{ is a CFG that generates } w\}$. Let $X$ be any context-free language. Prove that $X$ is decidable by building a decider for $X$. (Use $M$ and $X$ in your construction.)
- Let $A_\text{TM} = \{ \langle M, w\rangle \mid M \text{ is a TM that accepts } w\}$. Prove that $A_\text{TM}$ is recognizable by giving a description of a TM that recognizes it. Is your TM a decider? Explain why or why not.

## 4. [`r paste(fnames[7:9], sep = ',')`] 

Find a countably infinite collection of countably infinite disjoint subsets of $\mathbb{N}$. That is, give a description of an infinite sequence of subsets $X_1, X_2, X_3, \ldots$ of natural numbers such that $X_i \cap X_j = \emptyset$ whenever $i\neq j$ and such that each $X_i$ is countably infinite.

# Languages as Problems

## Emptiness problems

These languages are decidable. 

- $E_\text{DFA} = \{\langle A\rangle \mid A \text{ is a DFA and } L(A) = \emptyset\}$
- $E_\text{CFG} = \{ \langle G \rangle \mid G \text{ is a CFG and } L(G) = \emptyset \}$

In other words, the *emptiness problems* for DFA's and CFG's are decidable. A TM can tell if a DFA or CFG has an empty language.

## Equivalence problems

- $EQ_\text{DFA} = \{\langle A, B\rangle \mid A,B \text{ are DFA's and } L(A) = L(B)\}$ is decidable.

In other words, the *equivalence problem* for DFA's is decidable. A TM can tell if two DFA's generate the same language.

## Acceptance problems

These languages are decidable. 

- $A_\text{DFA} = \{\langle B,w \rangle \mid B\text{ is a DFA accepting } w \}$
- $A_\text{CFG} =  \{\langle G, w\rangle \mid G \text{ is a CFG generating } w\}$

In other words, the *acceptance problems* for DFA's and CFG's are decidable. A TM can tell if a given DFA or CFG recognizes a given string.

# An undecidable language

## $A_\text{TM}$ is undecidable

- $A_\text{TM} = \{ \langle M, w\rangle \mid M \text{ is a TM that accepts } w\}$ is recognizable (prework).
- Theorem: $A_\text{TM}$ is undecidable.
    - i.e., the acceptance problem for TM's is undecidable.
    
Proof (by contradiction) on board.

## Summary of proof

Suppose to the contrary that a TM $H$ decides $A_\text{TM}$.

- $H$ accepts $\langle M, w\rangle$ exactly when $M$ accepts $w$.
- $D$ rejects $\langle M \rangle$ exactly when $M$ accepts $\langle M \rangle$.
- $D$ rejects $\langle D \rangle$ exactly when $D$ accepts $\langle D \rangle$, a contradiction.

## Proof as a diagonalization argument

(on board)

# The halting problem

## The Halting Problem

Given $\langle M, w\rangle$ a description of a TM $M$ and a string $w$, is there a TM decider $T$ that will accept if $M$ halts on $w$ and reject if it doesn't?

Suppose there were. Then we could decide the acceptance problem:

- Given $\langle M, w\rangle$, run $T$ on $\langle M, w\rangle$.
- If $T$ indicates that $M$ will not halt on $w$, reject.
- Otherwise, run $M$ on $w$, and accept/reject accordingly.

Since the acceptance problem is undecidable, the halting problem must be also.


