---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(1820)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 1.1b: Regular Operations

Write your preliminary solutions to each problem on this sheet of paper (front and back). In addition, you may record any important facts and definitions, and include any questions that you have. Add additional sheets as necessary. For written prework, everyone should do every problem. The names in brackets indicate who is responsible for presenting the problem; one of these students will be chosen to explain the problem in class.

1. Draw a state diagram for a DFA with 3 states that recognizes $\{w \mid w \text{ ends in } \mathtt{01}\}$.

2. Draw a state diagram for a DFA with 2 states that recognizes $\{w \mid w \text{ has an odd number of symbols}\}$.

3. [`r paste(fnames[1:3], sep = ',')`] Apply the construction in the proof of Theorem 1.25 (page 45ff) to give a state diagram for a DFA with 6 states that recognizes $\{w \mid w \text{ ends in } \mathtt{01}\} \cup \{w \mid w \text{ has an odd number of symbols}\}$. Use your DFA's from questions 1 and 2.

4. [`r paste(fnames[4:6], sep = ',')`] Suppose that $A_1$ and $A_2$ are regular languages. Explain how to modify the proof of Theorem 1.25 to prove that (a) $A_1 \cap A_2$ is a regular language , and (b) $(A_1 \setminus A_2) \cup (A_2 \setminus A_1)$ is a regular language. (Note: $(A_1 \setminus A_2) \cup (A_2 \setminus A_1)$ is the set of all strings that are either in $A_1$ or in $A_2$, but not both.)

5. [`r paste(fnames[7:9], sep = ',')`] Give a state diagram for an NFA that recognizes $A$, where
$$A = \{ xy \mid x \text{ has an even number of 0's and } y \text{ has an odd number of 1's} \}. $$

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

