---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(1124)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Benjamin", "Grace", "Joshua"))
```

## Prework 1.2a: Nondeterminism

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:4], sep = ',')`] Refer to questions 1--3 of the last prework assignment. Use your DFA's from questions 1 and 2 and the construction in Figure 1.46 (page 59) to construct a state diagram for an NFA that recognizes the language 
$$
A = \{w \mid w \text{ ends in } \mathtt{01}\} \cup \{w \mid w \text{ has an odd number of symbols}\}.
$$
Does this NFA have the same number of states as the DFA for $A$ that you constructed in question 3 of the last prework? Will this always happen? Explain.

2. [`r paste(fnames[5:8], sep = ',')`] Construct a state diagram for a DFA that recognizes the language $A = \{\mathtt{01}, \mathtt{001}, \mathtt{010} \}$, then use the construction in Figure 1.50 (page 62) to convert it to a DFA that recognizes $A^*$. Check that your DFA works on a non-trivial element of $A^*$.

3. [`r paste(fnames[9:13], sep = ',')`] The power set $\mathcal{P}(A)$ is the set of all subsets of $A$. Fact: If $A$ has $n$ elements, then $\mathcal{P}(A)$ has $2^n$ elements. Write down all of the elements of $\mathcal{P}(\{c, u, b, s\})$ in an organized way that illustrates this fact.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

