---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(12120)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 1.4a: The Pumping Lemma

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Read Example 1.75 on page 81. The last line of the third paragraph states, "With condition 3 the proof follows because $y$ must consist of only \texttt{0}s, so $xyyz\not\in F$." Explain, in more detail than is given in the book, why $xyyz\not\in F$.

2. [`r paste(fnames[4:6], sep = ',')`] In the last sentence of Example 1.75, it says that the string $\mathtt{0}^p\mathtt{0}^p$ "can be pumped." Explain, what this means, and, specifically, how it can be pumped.

3. [`r paste(fnames[7:9], sep = ',')`] Use the Pumping Lemma to show that the language $A = \{www \mid w \in \{\mathtt{a},\mathtt{b}\}^*\}$ is not regular.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    