---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(12424)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 1.4b: More Pumping Lemma Proofs

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] We have shown that the language consisting of strings with the same number of 0's as 1's is nonregular. However, the following language is regular.
$$
A = \{w \mid w \text{ has the same number of 01 substrings as 10 substrings} \}
$$
Prove that $A$ is regular by finding a regular expression that describes it. 

2. [`r paste(fnames[4:6], sep = ',')`] A *palindrome* is a string that reads the same forwards as backwards. For example, 00011000 is a palindrome, but 101010 is not. Prove that the language
$$
A = \{w \mid w \text{ is not a palindrome}\}
$$
is not a regular language, where $\Sigma = \{0,1\}$.

3. [`r paste(fnames[7:9], sep = ',')`] We proved that the language $A = \{0^n1^n \mid n \geq 0\}$ is nonregular by pumping up. Redo this proof, but instead, pump down.

4. [`r paste(fnames[10:13], sep = ',')`] Prove that the following language is nonregular.
$$
A = \{\underbrace{1^n0^*1^n0^*1^n0^* \cdots 1^n}_{k \; 1^n\text{'s}} \mid k\geq 2, \; n\geq 0 \}
$$
Hint: Consider $A \cap (1^*01^*)$.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    