---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(12624)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 1.4c: Regular vs. Nonregular

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:2], sep = ',')`] Let $A = \{\mathtt{0}^ku\mathtt{0}^k \mid k \geq 1 \text{ and } u \in \{\mathtt{0,1}\}^*\}$. Prove that $A$ is regular.

2. [`r paste(fnames[3:4], sep = ',')`] Let $B = \{\mathtt{0}^k\mathtt{1}u\mathtt{0}^k \mid k \geq 1 \text{ and } u \in \{\mathtt{0,1}\}^*\}$. Prove that $B$ is nonregular.

3. [`r paste(fnames[5:7], sep = ',')`] Let $\Sigma = \{\mathtt{0,1}\}$. For each $k \geq 1$, let $C_k$ be the language consisting of all strings that contain a \texttt{0} exactly $k$ places from the right-hand end. Build a DFA that recognizes $C_k$. What is the fewest number of states required?

4. [`r paste(fnames[8:10], sep = ',')`] How could the solution to Problem 3 be different if $C_k$ were the language consisting of all strings that contain a \texttt{0} exactly $k$ places from the \textit{left}-hand end?

5. [`r paste(fnames[11:13], sep = ',')`] Consider $\Sigma = \left\lbrace \frac{0}{0}, \frac{0}{1}, \frac{1}{0}, \frac{1}{1}  \right\rbrace$. A string in $\Sigma^\ast$ consists of a top binary string $t$ and a bottom binary string $b$ of equal lengths. For this problem, we regard $t$ and $b$ as numbers expressed in binary notation. Prove that the following language $F$ is regular.
$$
F = \left\{ w = \frac{t}{b} \in \Sigma^\ast \mid b = 3t \right\} 
$$
Hint: It might be easier to prove that $F^R$ is regular, and use closure.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    