---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(13120)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 2.1a: Context-Free Grammars

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. Consider the grammar over $\Sigma = \{\text{Moe}, \text{Larry}, \text{Curly}, \text{hit}, \text{poked}, \text{kicked}\}$ with the following three rules.
\begin{align*}
S & \rightarrow N \; V \; N \\
N & \rightarrow \text{Moe} \mid \text{Larry} \mid \text{Curly} \\
V & \rightarrow \text{hit} \mid \text{poked} \mid \text{kicked}
\end{align*}
Give a derivation for the string "Moe kicked Larry".

Problems 2 and 3 refer to the following grammar with terminals $\Sigma = \{\mathtt{a}, +, \ast, \mathtt{(}, \mathtt{)}\}$.
\begin{align*}
E & \rightarrow E + T \mid T \\
T & \rightarrow T \ast F \mid F \\
F & \rightarrow \mathtt{(} E \mathtt{)} \mid \mathtt{a}
\end{align*}

2. [`r paste(fnames[1:3], sep = ',')`] Give a derivation for the string $\mathtt{a}+\mathtt{a}+\mathtt{a}$, and illustrate your derivation with a tree (or some other way).

3. [`r paste(fnames[4:6], sep = ',')`] Give a derivation for the string $((\mathtt{a}))$, and illustrate your derivation with a tree (or some other way).

4. [`r paste(fnames[7:9], sep = ',')`] Define a grammar that describes the set of all palindromes in $\Sigma = \{\mathtt{0}, \mathtt{1}\}$, and give a derivation for $\mathtt{0110}$.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    