---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(2824)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 2.2b: Building a PDA for a CFG

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Use the procedure in the proof of Lemma 2.21 to build a state diagram for a PDA that recognizes the language described by the following CFG. The start variable is $E$ and the terminals are $\Sigma = \{\mathtt{a}, +, \ast, \mathtt{)}, \mathtt{(}\}$.
\begin{align*}
E & \rightarrow E + T \mid T \\
T & \rightarrow T \ast F \mid F \\
F & \rightarrow \mathtt{(} E \mathtt{)} \mid \mathtt{a}
\end{align*}

2. [`r paste(fnames[4:6], sep = ',')`] Use the procedure in the proof of Lemma 2.21 to build state diagram for a PDA that recognizes the language described by the following CFG. The start variable is $R$.
\begin{align*}
R & \rightarrow XRX \mid S \\
S & \rightarrow \mathtt{a}T\mathtt{b} \mid \mathtt{b}T\mathtt{a} \\
T & \rightarrow XTX \mid X \mid \varepsilon \\
X & \rightarrow \mathtt{a} \mid \mathtt{b}
\end{align*}

3. [`r paste(fnames[7:9], sep = ',')`] In this problem you will show that the set of context-free languages is closed under the regular operations. Let $G_1 = (V_1, \Sigma, R_1, S_1)$ and $G_2 = (V_2, \Sigma, R_2, S_2)$ be CFG's that describe the languages $A_1$ and $A_2$, respectively, where $V_1 \cap V_2 = \emptyset$. (Hint: For each part (a)-(c), add a new start state $S$ and a new first rule.)
    a. Give a CFG that describes $A_1 \cup A_2$. 
    b. Give a CFG that describes $A_1 \circ A_2$. 
    c. Give a CFG that describes $A_1^*$. 
    
4. [`r paste(fnames[10:13], sep = ',')`] Consider the following grammar. The start state is $S$.
\begin{align*}
S & \rightarrow \varepsilon \mid \mathtt{0}S\mathtt{1} \mid SAS \mid \mathtt{111} \\
A & \rightarrow \mathtt{1}A{0} \mid \mathtt{0} \mid \mathtt{010} \mid ASA
\end{align*}
Recall that the *height* of a tree is the length of the longest path from the root to a leaf. What is the length of the largest string that a parse tree of height 5 can derive?

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    