---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(22124)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 3.2a: Turing Machine Variants

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Suppose that $M_1$ is a TM that recognizes a language $A_1$ and $M_2$ is a TM that recognizes a language $A_2$. How can the following TM fail to recognize the concatenation $A_1 \circ A_2$? How can you fix it? (Hint: It works fine if $M_1$ and $M_2$ are deciders.)

\begin{quote}
 On input $w$, \\
 1. For each way of splitting $w$ into two parts $w_1,w_2$: Do steps 2--4. 
 \begin{quote}
     2. Run $M_1$ on $w_1$.\\
     3. Run $M_2$ on $w_2$.\\
     4. If both 2 and 3 accept, then accept $w$.
 \end{quote}
 5. Reject $w$ if no acceptance is made in step 4 for any split.
\end{quote}

2. [`r paste(fnames[4:6], sep = ',')`] How many different ways can you divide the string $\mathtt{abcd}$ into nonempty substrings $w_1, w_2, \ldots, w_k$, for $k \geq 1$, such that $w_1w_2\cdots w_k = w$? How about $\mathtt{abcde}$? Can you describe an organized method for running through each possible division?

3. [`r paste(fnames[7:9], sep = ',')`] Let $M_3$ be a TM that recognizes a language $B$. Explain how to build a TM that recognizes $B^\ast$. 

4. [`r paste(fnames[10:13], sep = ',')`] Suppose that $M_4$ is a TM that decides a language $C$. Describe a simple way to construct a TM that decides $\overline{C}$, the complement of $C$. Explain why this construction would not be so simple if $M$ were just a recognizer, and not a decider.


\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    