---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(22620)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 4.1a: Decidable Languages

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Let $X_1 = \{\langle A \rangle \mid A \text{ is a DFA and } L(A) = \{\texttt{0}, \texttt{1}\}^\ast \}$. Show that $X_1$ is decidable.

2. [`r paste(fnames[4:6], sep = ',')`] Let $X_2 = \{\langle A, B\rangle \mid A,B \text{ are DFA's and } L(A) \subseteq L(B)\}$. Show that $X_2$ is decidable.

3. [`r paste(fnames[7:9], sep = ',')`] Consider the following grammar.
\begin{align*}
S & \rightarrow UV \\
V & \rightarrow VV \\
U & \rightarrow WU \\
U & \rightarrow \mathtt{a} \\
V & \rightarrow \mathtt{b} \\
W & \rightarrow \mathtt{c}
\end{align*}
    a. Explain why the derivation of any string of length $n$ derived by this grammar requires exactly $2n-1$ steps.
    b. Simplify the grammar into an equivalent grammar with as few rules as possible.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    