---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(3424)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 4.1b: Countable Sets

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. Explain why the floor function $f : \mathbb{R} \longrightarrow \mathbb{N}$ given by $f(x) = \lfloor x \rfloor$ is not one-to-one.

2. [`r paste(fnames[1:3], sep = ',')`] Prove that the integers $\mathbb{Z}$ are countable.

3. [`r paste(fnames[4:6], sep = ',')`] Recall the argument that shows that $\mathbb{Q}$ is countable. Generalize the argument to show that $X \times Y$ is countable, for any countable $X$ and $Y$. Conclude that $X_1 \times X_2 \times \cdots \times X_n$ is countable for a finite collection of countable sets $X_i$. (Recall that $X \times Y$ is the set of all ordered pairs $(x,y)$ with $x \in X$ and $y\in Y$.)

4. [`r paste(fnames[7:9], sep = ',')`] Is the set of all polynomials $a_0 + a_1x + \cdots + a_nx^n$ with integer coefficients countable? Justify your answer.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    