---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(3220)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 4.2a: Uncountability and non-recognizable languages

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Let $\mathcal{B}$ be the set of all infinite binary sequences. Use a diagonalization argument to explain why $\mathcal{B}$ is uncountable.

2. Recall that a \textit{one-to-one correspondence} is a function that is both one-to-one and onto. Describe a natural one-to-one correspondence $f:\mathcal{B} \longrightarrow \mathcal{P}(\mathbb{N})$, where $\mathcal{P}(\mathbb{N})$ is the power set of $\mathbb{N}$ and $\mathcal{B}$ is the set of all infinite binary sequences. (This shows that $\mathcal{P}(\mathbb{N})$ is uncountable.)

3. [`r paste(fnames[4:6], sep = ',')`] 
    a. In class we described a TM $M$ that decided the language $A_\text{CFG} = \{\langle G, w \rangle \mid G \text{ is a CFG that generates } w\}$. Let $X$ be any context-free language. Prove that $X$ is decidable by building a decider for $X$. (Use $M$ and $X$ in your construction.)
    b. Let $A_\text{TM} = \{ \langle M, w\rangle \mid M \text{ is a TM that accepts } w\}$. Prove that $A_\text{TM}$ is recognizable by giving a description of a TM that recognizes it. Is your TM a decider? Explain why or why not.

4. [`r paste(fnames[7:9], sep = ',')`] Find a countably infinite collection of countably infinite disjoint subsets of $\mathbb{N}$. That is, give a description of an infinite sequence of subsets $X_1, X_2, X_3, \ldots$ of natural numbers such that $X_i \cap X_j = \emptyset$ whenever $i\neq j$ and such that each $X_i$ is countably infinite.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    