---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(31620)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 5.1a: Reduction Arguments

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Let $\mathit{CFL}_\text{TM} = \{ \langle M \rangle \mid M \text{ is a TM and } L(M) \text{ is context free}\}$. Show that $\mathit{CFL}_\text{TM}$ is undecidable by showing that $A_\text{TM}$ reduces to $\mathit{CFL}_\text{TM}$. (Hint: Mimic the reduction argument for $\mathit{REGULAR}_\text{TM}$.)

2. [`r paste(fnames[4:6], sep = ',')`] During the course of a computation, we say that a TM *erases* if it ever writes a blank symbol on its tape. Let $\mathit{ERASE}_\text{TM} = \{ \langle M, w \rangle \mid M \text{ erases when run on input } w \}$. Show that $\mathit{ERASE}_\text{TM}$ is undecidable by showing that $A_\text{TM}$ reduces to $\mathit{ERASE}_\text{TM}$. (Hint: Look at Problem 5.10 and its solution in the text.)

3. [`r paste(fnames[7:9], sep = ',')`] Recall that in our definition of a TM, we specified that the tape head does not move if, during the course of a computation, it is instructed to move left when it is already at the beginning of the tape. Call such an event a *thud*. Let $\mathit{THUD}_\text{TM} = \{ \langle M, w \rangle \mid M \text{ thuds when run on input } w\}$. Show that $\mathit{THUD}_\text{TM}$ is undecidable by showing that $A_\text{TM}$ reduces to $\mathit{THUD}_\text{TM}$. 

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    