---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(31820)
fnames <- sample(c("Sam", "James", "Drake", "Wesley", "Sophia", "Carolyn", "Trevor", "Tristan", "Ryley"))
```

## Prework 5.2a: Arguments using Computation Histories

Write your preliminary solutions to each problem on this sheet of paper (front and back). Use additional sheets if necessary. The names in brackets indicate the subset responsible for presenting the problem.

1. Give an implementation description of a Turing Machine that does not satisfy the conclusion of Lemma 5.8.

2. [`r paste(fnames[1:3], sep = ',')`] In the proof of Theorem 5.10 on page 224, the book says, "The second condition is hardest to check." Read the description of this step, and explain in your own words why an LBA can do this, and a TM is not needed.

3. [`r paste(fnames[4:6], sep = ',')`] Read the proof of Theorem 5.13 (pp. 225--226). Many parts of this proof are not explained in detail. Identify what you consider to be the vaguest sentence in this proof, and give a reason for your choice. What do you think needs to be explained in more detail? 

4. [`r paste(fnames[7:9], sep = ',')`] Show that $\mathit{ALL}_\text{CFG}$ reduces to $\mathit{EQ}_\text{CFG}$. What does this prove about the decidability of $\mathit{EQ}_\text{CFG}$?

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    