---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(32724)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 5.3a: Mapping Reducibility

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Let $A = \{\mathtt{a}^n\mathtt{b}^n \mid n\geq 1\}$ and $B = \{a, b\}$.
    a. Show tht $A \leq_\text{m} B$ by defining a computable function $f:\Sigma^\ast \longrightarrow \Sigma^*$ such that $w\in A$ exactly when $f(w)\in B$.
    b. Similarly, show that $B \leq_\text{m} A$.
    c. Parts (a) and (b) show that $\leq_\text{m}$ is not *antisymmetric*, so it is not a partial order. Is $\leq_\text{m}$ *transitive*? (See p. 9.)

2. [`r paste(fnames[4:6], sep = ',')`] Recall that a language is *closed under reversal* if, for every $w$ in the language, its reverse $w^R$ is also in the language. Let $\mathit{CUR}_\text{TM} = \{\langle M \rangle \mid M \text{ is a TM and } L(M) \text{ is closed under reversal}\}$. Show that $\mathit{CUR}_\text{TM}$ is undecidable by showing that $A_\text{TM} \leq_\text{m} \mathit{CUR}_\text{TM}$. (Hint: Map the string $\langle M, w\rangle$ to the string $\langle M_w \rangle$, where $M_w$ is a TM that recognizes a simple closed-under-reversal language exactly when $M$ accepts $w$.) 

3. [`r paste(fnames[7:9], sep = ',')`] In Prework 4.2b we showed that $\mathit{CUR}_\text{DFA}$ is decidable by using a decider for $\mathit{EQ}_\text{DFA}$.  Following this argument, give an alternative proof that $\mathit{EQ}_\text{TM}$ is undecidable by showing that $\mathit{CUR}_\text{TM}$ reduces to $\mathit{EQ}_\text{TM}$.

4. [`r paste(fnames[10:13], sep = ',')`] Let $\Sigma = \{\mathtt{0},\mathtt{1}\}$. Show that a language $A$ is decidable if and only if $A \leq_\text{m} \{\mathtt{0}^\ast\mathtt{1}^\ast\}$. 

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    