---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(4324)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 5.3b: Mapping reducibility and recognizability proofs

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:2], sep = ',')`] Show that $\overline{E_\text{TM}}$ is recognizable by describing a TM that accepts $\langle M \rangle$ whenever $L(M) \neq \emptyset$. What does your TM do if $L(M) = \emptyset$?

2. [`r paste(fnames[3:5], sep = ',')`] Show that a language $A$ is recognizable if and only if $A \leq_\text{m} A_\text{TM}$.

3. [`r paste(fnames[6:8], sep = ',')`] Let $J = \{w \mid w=\mathtt{0}x \text{ for some } x\in A_\text{TM}\text{, or } w=\mathtt{1}y \text{ for some } y \in \overline{A_\text{TM}}\}$.
    a. Show that $J$ is not recognizable by showing that $\overline{A_\text{TM}} \leq_\text{m} J$. 
    b. Show that $\overline{J}$ is not recognizable by showing that $A_\text{TM} \leq_\text{m} J$. 

4. [`r paste(fnames[9:11], sep = ',')`] Let $J$ be as given in #3. Show that $J \leq_\text{m} \overline{J}$.

5. [`r paste(fnames[12:13], sep = ',')`] Let $X = \{\langle M, w\rangle \mid M \text{ is a single-tape TM that never writes over its input when computing on }w\}$. Suppose (to the contrary) that $D$ is a TM that decides $X$. Describe how to use $D$ to build a TM $E$ that decides $A_\text{TM}$. What does this prove about $X$? 

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    