---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(41024)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 7.1a: Running Time

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] The \text{length} of a tape of a Turing machine is the number of symbols on the tape before the infinite sequence of blank symbols. So when a TM starts on an input of length $n$, its tape has length $n$, but then the length could grow during execution. Suppose a TM has running time $O(n^3)$. Give an asymptotic bound for the maximum length of its tape at any time in its execution. Explain why, in general, your bound can't be any less than it is. 

2. [`r paste(fnames[4:6], sep = ',')`] Review the construction of a single-tape TM that simulates a multitape TM in the Proof of Theorem 3.13 (p. 177). Consider a multitape TM $M$ with 3 tapes, and the single tape TM $S$ that simulates it. Suppose that one of the transitions is given by $\delta(q_4, \mathtt{1,1,1}) = (q_5, \mathtt{x,x,x}, \text{R,R,L})$. If the tape of $S$ looks like this
$$
\mathtt{\#010\stackrel{\bullet}{1}0\#011\stackrel{\bullet}{1}\#010\stackrel{\bullet}{1}01\#}\sqcup\cdots
$$
when $S$ in in state $q_4$, what is on the tape after one step of execution? How many passes over the tape did $S$ have to do to make this step?

3. [`r paste(fnames[7:9], sep = ',')`] Read the discussion on the top of p. 278. Then explain why $n^5 16^{n^5} = 2^{O(n^5)}$.

4. [`r paste(fnames[10:13], sep = ',')`] Use Definition 7.5 to show that $2^n = o(4^n)$. Is $4^n = O(2^n)$? How about $4^n = 2^{O(n)}$?

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    