---
geometry: left=0.75in, right=0.75in, top=0.8in, bottom=0.4in
classoption: twoside
output: 
  pdf_document:
    keep_tex: false
    includes:
      in_header: preworkheader.tex
---

```{r include=FALSE}
set.seed(41724)
fnames <- sample(c("Ky", "Curtis", "Micah", "Todd", "Andrew", "Meghan", "Allie", "David", "Connor", "Levi", "Ben", "Grace", "Joshua"))
```

## Prework 7.2b: More Languages in $\text{P}$

Write your preliminary solutions to each problem and submit a PDF on Canvas. The names in brackets indicate the subset responsible for presenting the problem.

1. [`r paste(fnames[1:3], sep = ',')`] Consider the following context-free grammar.
\begin{align*}
S & \rightarrow AB \\
A & \rightarrow AA \mid \mathtt{1} \\
B & \rightarrow BA \mid \mathtt{0}
\end{align*}
    a. Complete the table produced by the algorithm in the proof of Theorem 7.16 on the input $w = \mathtt{11011}$. Does the algorithm accept (i.e., is $\mathtt{11011}$ generated by this grammar)?
    b. Repeat part (a) for the string $\mathtt{01101}$.

2. [`r paste(fnames[4:6], sep = ',')`]  Recall that $\mathit{ALL}_\text{DFA} = \{ \langle M \rangle \mid M \text{ is a DFA and } L(M) = \Sigma^\ast\}$. Show that $\mathit{ALL}_\text{DFA} \in \text{P}$ by describing a polynomial-time decider. (Hint: Use the polynomial-time decider for $\mathit{PATH}$ as a subroutine).

3. [`r paste(fnames[7:9], sep = ',')`]  Recall that $\mathit{EQ}_\text{DFA} = \{ \langle P, Q \rangle \mid P,Q \text{ are DFA's and } L(P) = L(Q)\}$. Show that $\mathit{EQ}_\text{DFA} \in \text{P}$. (Hint: show that every step of the algorithm described in the proof of Theorem 4.5 is polynomial time, including the algorithm from the proof of Theorem 4.4.)

4. [`r paste(fnames[10:13], sep = ',')`] A *triangle* in an undirected graph is a set of 3 vertices that all share edges with each other. Let $\mathit{TRIANGLE} = \{\langle G \rangle \mid G \text{ is a graph that contains a triangle}\}$. Show that $\mathit{TRIANGLE} \in \text{P}$ by describing an algorithm for it and showing that it is polynomial time.

\medskip
\mbox{}\xrfill[2pt]{1pt}\textsc{\small begin your solutions below this line}\xrfill[2pt]{1pt}\mbox{}

    